### ISSUE TITLE
Broken backwards compatibility between nemo versions 2.5.0 and 2.7.X (NEMO ASR)

### ISSUE THREAD

**Issue by diarray-hub** [NVIDIA-NeMo/NeMo#15658]
Hi,

It seems there was a change in the name of a parameter in decoding.greedy.boosting_tree between version 2.5.0 and 2.7.3 (I didn't try to pinpoint the specific version that introduces the change, it might have happened earlier). Specifically the the parameter "key_phrase_items_list" was changed to "key_phrases_list" resulting in the following error when you try to when you try to load a pretrained model:

`omegaconf.errors.ConfigAttributeError: Key 'key_phrase_items_list' is not in struct
        full_key: decoding.greedy.boosting_tree.key_phrase_items_list
        object_type=dict. Did you mean: 'key_phrases_list'?
`

It seems the backwards compatibility was broken somewhere between these two versions, because I can load other checkpoints trained with version 2.3.0 with the latest nemo version without any error. But none of the models I trained with the 2.5.0 version can pass the .from_pretraining() method without encountering the above error in nemo-toolkit version 2.7.3.

If anyone encounters the same issue or has a fix to suggest, please help. I wanted to open an issues so this can be resolved for future versions.

**Comment by diarray-hub** [comment]
Any luck on this? The problem seems more general than I thought, I'm also unable to load pretrained slu_conformer_transformer_large_slurp model due to a similar unexpected key error:  `AttributeError: 'MultiLayerPerceptron' object has no attribute 'mlp'`. All these errors are happening in the `nemo/core/connectors/save_restore_connector.py`module. And I really don't understand them. Seems like a mismatch between the saved configs and the arguments the classes in the newest versions actually expect. Or is it a fault on my end? 

I would greatly appreciate any help on this!

PS: this second error with the slurp model is happening even with nemo 2.5.0; I don't know if there is a version of nemo for which it doesn't occur but I'm guessing it was working on some earlier version. Just like the ASR pretrained loading working fine with 2.5.0 and failing for above versions

**Comment by diarray-hub** [comment]
Hey everyone,

If you are not an OG nemo user, who has  trained ASR models since nemo 1.20.0 and has a bunch of old_checkpoint that you still use, you will likely never encounter the issue above. So I doubt it will be fixed anytime soon. To be more precise, you'll likely only encounter this issue if you have checkpoints trained with nemo 2.5.0.

TL;DR: Somewhere around 2.5.0 NeMo added a context-biasing feature (boosting_tree) to its decoding codebase, and it originally had a named parameter: **`key_phrases_list`**. That name was quickly changed in the following releases to key_phrase_items_list. When NeMo instantiates the model config using OmegaConf, it enforces struct validation. 

Models trained with 2.5.0 lack the expected key_phrase_items_list key in their config causing a strict configuration crash before strict=False even has a chance to bypass it. Funny situation because models trained with older nemo versions (before the context-biasing feature was introduced) generally load fine. To fix this, you must download the configuration dictionary, patch the missing structural field, and load the model with its pacthed configuration. The code below is a fix to 

> 
	omegaconf.errors.ConfigAttributeError: Key 'key_phrase_items_list' is not in struct
    		full_key: decoding.greedy.boosting_tree.key_phrase_items_list
    		object_type=dict, Did you mean: 'key_phrases_list'? 

```python
import os
from omegaconf import OmegaConf
from nemo.collections.asr.models import ASRModel

model_name = <MODEL_ID>

# Download the configuration dictionary from the remote checkpoint
cfg = ASRModel.from_pretrained(model_name, return_config=True)

# Disable struct enforcement to safely inject the missing validation parameter
OmegaConf.set_struct(cfg, False)

if "decoding" in cfg and "greedy" in cfg.decoding:
    if "boosting_tree" in cfg.decoding.greedy:
        cfg.decoding.greedy.boosting_tree.key_phrase_items_list = None

if "decoding" in cfg and "beam" in cfg.decoding:
    if "boosting_tree" in cfg.decoding.beam:
        cfg.decoding.beam.boosting_tree.key_phrase_items_list = None

# Save the patched configuration locally
temp_config_path = "patched_config.yaml"
OmegaConf.save(config=cfg, f=temp_config_path)

asr_model = ASRModel.from_pretrained(
    model_name=model_name,
    override_config_path=absolute/path/to/temp_config_path,
    strict=False
)

# OPTIONAL: Clean up the temporary file after successful instantiation
if os.path.exists(temp_config_path):
    os.remove(temp_config_path)
```

This fix even worked on the latest 3.0.0 release
